export const STRAPI_ENDPOINT = process.env.NEXT_PUBLIC_STRAPI_ENDPOINT;
export const STRAPI_GRAPHQL_API_ENDPOINT =
  process.env.NEXT_PUBLIC_STRAPI_GRAPHQL_API_ENDPOINT;
export const STRAPI_API_TOKEN = process.env.NEXT_PUBLIC_STRAPI_API_TOKEN;
